%prep error
logs in copr build:
```
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.nJSwXx
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf rclone-1.73.2
+ /usr/bin/gzip -dc /builddir/build/SOURCES/rclone-v1.73.2.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd rclone-1.73.2
/var/tmp/rpm-tmp.nJSwXx: line 41: cd: rclone-1.73.2: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.nJSwXx (%prep)
```

this pointed to it looking for a file `rclone-1.73.2` that doesn't exist,
but the tarball extracts to `rclone-v1.73.2`. This is because the `Source` tag in the spec file is
using `%{name}-v%{version}.tar.gz` instead of `%{name}-%{version}.tar.gz`.
Changing the `Source` tag to match the actual tarball name should fix the issue.